// Auto-generated by `pnpm cf:typegen` — do not edit manually.
// Run `pnpm cf:typegen` after changing wrangler.jsonc to regenerate.
interface CloudflareEnv {
  DB: D1Database;
  BUCKET: R2Bucket;
  ADMIN_JWT_SECRET: string;
  R2_PUBLIC_DOMAIN: string;
}
